name: 🚀 Deploy staging on push dev

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      # - name: 🔨 Build Project
      #   run: |
      #     npm install
      #     npm run build

      - name: List output files
        run: find / -print

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.DEPLOY_FTP_USERNAME }}
          password: ${{ secrets.DEPLOY_FTP_PASSWORD }}
          local-dir: /
